# galera-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera
spec:
  selector:
    app.kubernetes.io/name: mariadb-galera
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
